package com.bancodebogota.consultarmoras;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 11g Release 2 11.1.2.1.0.6081

public class ConsultarMorasModelBeanPortClient
{
  public static void main(String [] args)
  {
    ConsultarMorasModelBeanService consultarMorasModelBeanService = new ConsultarMorasModelBeanService();
    ConsultarMorasModelBean consultarMorasModelBean = consultarMorasModelBeanService.getConsultarMorasModelBeanPort();
    // Add your code to call the desired methods.
  }
}
