
package com.bancodebogota.consultarmoras;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ConsultarMorasModelBeanService", targetNamespace = "http://modelopersistencia.sesion.consultarmoras.bancodebogota.com/", wsdlLocation = "http://w8sici009:7101/ConsultarMorasService-ConsultaMorasService-webapp/ConsultarMorasModelBeanService/#%7Bhttp%3A%2F%2Fmodelopersistencia.sesion.consultarmoras.bancodebogota.com%2F%7DConsultarMorasModelBeanService?wsdl")
public class ConsultarMorasModelBeanService
    extends Service
{

    private final static URL CONSULTARMORASMODELBEANSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.bancodebogota.consultarmoras.ConsultarMorasModelBeanService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.bancodebogota.consultarmoras.ConsultarMorasModelBeanService.class.getResource(".");
            url = new URL(baseUrl, "http://w8sici009:7101/ConsultarMorasService-ConsultaMorasService-webapp/ConsultarMorasModelBeanService/#%7Bhttp%3A%2F%2Fmodelopersistencia.sesion.consultarmoras.bancodebogota.com%2F%7DConsultarMorasModelBeanService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://w8sici009:7101/ConsultarMorasService-ConsultaMorasService-webapp/ConsultarMorasModelBeanService/#%7Bhttp%3A%2F%2Fmodelopersistencia.sesion.consultarmoras.bancodebogota.com%2F%7DConsultarMorasModelBeanService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CONSULTARMORASMODELBEANSERVICE_WSDL_LOCATION = url;
    }

    public ConsultarMorasModelBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarMorasModelBeanService() {
        super(CONSULTARMORASMODELBEANSERVICE_WSDL_LOCATION, new QName("http://modelopersistencia.sesion.consultarmoras.bancodebogota.com/", "ConsultarMorasModelBeanService"));
    }

    /**
     * 
     * @return
     *     returns ConsultarMorasModelBean
     */
    @WebEndpoint(name = "ConsultarMorasModelBeanPort")
    public ConsultarMorasModelBean getConsultarMorasModelBeanPort() {
        return super.getPort(new QName("http://modelopersistencia.sesion.consultarmoras.bancodebogota.com/", "ConsultarMorasModelBeanPort"), ConsultarMorasModelBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarMorasModelBean
     */
    @WebEndpoint(name = "ConsultarMorasModelBeanPort")
    public ConsultarMorasModelBean getConsultarMorasModelBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://modelopersistencia.sesion.consultarmoras.bancodebogota.com/", "ConsultarMorasModelBeanPort"), ConsultarMorasModelBean.class, features);
    }

}
