
package com.bancodebogota.consultarmoras;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://modelopersistencia.sesion.consultarmoras.bancodebogota.com/")
public class Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.bancodebogota.consultarmoras.types.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Exception(String message, com.bancodebogota.consultarmoras.types.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Exception(String message, com.bancodebogota.consultarmoras.types.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bancodebogota.consultarmoras.types.Exception
     */
    public com.bancodebogota.consultarmoras.types.Exception getFaultInfo() {
        return faultInfo;
    }

}
